mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  #  type-aliases-package: com.mybatis.bean
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/transaction_test?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                    #数据库连接池最小维持连接数
      initial-size: 5                #初始化连接数库
      max-total: 5                   #最大连接数
      max-wait-millis: 200